# Generated by Django 6.1 on 2026-08-29 13:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HSCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Code SH')),
                ('description', models.TextField(verbose_name='Description')),
                ('section', models.CharField(blank=True, max_length=10)),
                ('chapter', models.CharField(blank=True, max_length=10)),
                ('heading', models.CharField(blank=True, max_length=10)),
                ('tariff_category', models.CharField(blank=True, max_length=5)),
                ('is_excise_applicable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Code SH',
                'verbose_name_plural': 'Codes SH',
                'db_table': 'customs_hs_code',
            },
        ),
        migrations.CreateModel(
            name='LegalSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre du document')),
                ('reference', models.CharField(max_length=100, verbose_name='Référence officielle')),
                ('issuing_body', models.CharField(max_length=100, verbose_name='Organisme émetteur')),
                ('publication_date', models.DateField()),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Source Légale',
                'verbose_name_plural': 'Sources Légales',
                'db_table': 'customs_legal_source',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la règle')),
                ('priority', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Règle de Calcul',
                'verbose_name_plural': 'Règles de Calcul',
                'db_table': 'customs_rule',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='TaxComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la taxe')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code unique')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Composante Fiscale',
                'verbose_name_plural': 'Composantes Fiscales',
                'db_table': 'customs_tax_component',
            },
        ),
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_string', models.CharField(max_length=20, verbose_name='Version')),
                ('base_formula', models.TextField(help_text='e.g. CIF * rate', verbose_name='Formule de base')),
                ('default_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('condition_expression', models.TextField(blank=True, help_text="e.g. tariff_category == 'I'", verbose_name='Expression de condition')),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('UNDER_REVIEW', 'En révision'), ('APPROVED', 'Approuvé (Attente validation expert)'), ('ACTIVE', 'Actif'), ('RETIRED', 'Retiré'), ('NEEDS_EXPERT_VALIDATION', 'Nécessite Validation Expert')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customs_engine.legalsource')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='customs_engine.rule')),
            ],
            options={
                'verbose_name': 'Version de Règle',
                'verbose_name_plural': 'Versions de Règle',
                'db_table': 'customs_rule_version',
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='tax_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='customs_engine.taxcomponent'),
        ),
    ]
