# Generated by Django 6.1 on 2026-08-29 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('customs_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PROCESSING', 'En cours'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=20)),
                ('cif_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valeur CIF')),
                ('fob_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valeur FOB')),
                ('freight', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Fret')),
                ('insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Assurance')),
                ('total_taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Taxes')),
                ('total_to_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total à Payer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations_created', to=settings.AUTH_USER_MODEL)),
                ('hs_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='simulations', to='customs_engine.hscode')),
            ],
            options={
                'verbose_name': 'Simulation',
                'verbose_name_plural': 'Simulations',
                'db_table': 'simulations_simulation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine_version', models.CharField(default='1.0.0', max_length=50)),
                ('rules_version_stamp', models.CharField(max_length=100)),
                ('breakdown_payload', models.JSONField(verbose_name='Détail du calcul gelé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='simulations.simulation')),
            ],
            options={
                'verbose_name': 'Instantané de Calcul',
                'verbose_name_plural': 'Instantanés de Calcul',
                'db_table': 'simulations_snapshot',
            },
        ),
    ]
